swagger: '2.0'
info:
  title: APICARTO AOC
  description: >
    Le service d'interrogation du cadastre permet de faire le croisement entre un polygone et la couche des AOC/IGP. 
    Les données proviennent de France Agrimer et de l'INAO.
    Possibilité d'utiliser les communes de l'IGN ou les communes OSM
    
    
     ```json
        {"type":"FeatureCollection",
         "features":
          [{"type":"Feature",
           "geometry":
           {"type":"MultiPolygon","coordinates":[...]},
          "properties":{
             "area_inter":xxx,
             "appellation":"XXX",
             "id_uni":"X-XX-XXXX"
          }
        ]}
       }
  
    ```



    
  version: 1.0.0
  contact:
    name: Apicarto AOC
  license:
    name: AGPL-V3
    url: https://www.gnu.org/licenses/agpl-3.0.html
host: apicarto.sgmap.fr
consumes: application/json
schemes:
  - https
basePath: /
produces:
  - application/json
paths:
  /aoc/api/beta/in:
    post:
      description: |
        Prends une geometrie de type GeoJSON en paramètre d'entrée geom
        
        Paramètres de sorties : Retourne un résultat de Type "FeatureCollection" 
      tags:
        - Appelations
      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/AOC'
  
definitions:
  Geometry:
    type: object
    description: Une `Geometry` au sens GeoJSON
    externalDocs:
      url: http://geojson.org/geojson-spec.html#geometry-objects
      description: La documentation officielle du type `Geometry` de GeoJSON
    properties:
      type:
        type: string
        enum:
        - MultiPolygon
        - Point
        description: Le type corresponds au type de Géométrie(MultiPolygon ou Point)
      coordinates:
        type: array
        items:
          type: array
          items:
            type: number

  Feature:
    type: object
    description: Une `Feature` au sens GeoJSON
    externalDocs:
      url: http://geojson.org/geojson-spec.html#feature-objects
      description: La documentation officielle du type `Feature` de GeoJSON
    properties:
      type:
        type: string
        enum:
        - Feature
        description: La valeur de type est "Feature"
      id:
        type: string
      geometry:
        $ref: '#/definitions/Geometry'
      properties:
        type: object

  FeatureCollection:
    type: object
    description: Une `FeatureCollection` au sens GeoJSON
    externalDocs:
      url: http://geojson.org/geojson-spec.html#feature-collection-objects
      description: La documentation officielle du type `FeatureCollection` de GeoJSON
    properties:
      type:
        type: string
        enum:
        - Feature
        description: Le type est FeatureCollection
      features:
        type: array
        items: object

  AOC:
    description: ''
    allOf:
    - $ref: '#/definitions/Feature'
    - properties:
        properties:
          type: object
          properties:
            area :
              type: number
              format: float
            idapp:
                type: string
            id_uni:
                type: string
                description: corresponds à "segment-idapp-insee"
            insee:
                type: string
            segment:
                type: string
            instruction_obligatoire:
                 type: boolean
            granularite: 
                 type: string
            contains:
                 type: boolean     
                 
