swagger: '2.0'

info:
  title: APICarto AOC
  description: >
    Le module AOC permet de récupérer les AOC viticole de l'INAO intersectant une géométrie GeoJSON.

    Les données sources sont les [Délimitation Parcellaire des AOC Viticoles de l'INAO](https://www.data.gouv.fr/fr/datasets/delimitation-parcellaire-des-aoc-viticoles-de-linao/)


    **ATTENTION** : Cette fonctionnalité diffère de la première version d'APICARTO (/aoc/api/beta/in). Il manque dans les données libres l'attribut "segment" qui permettait d'enrichir les données avec l'attribut "granularite" ('exacte' ou 'commune') nécessaire aux traitements métiers de l'INAO.

  version: '1.0'


consumes:
  - application/json
produces:
  - application/json

basePath: /api

paths:
  /aoc/appellation-viticole:
    post:
      description: |
        Prends une geometrie de type GeoJSON en paramètre d'entrée geom et renvoie les appellations viticoles intersectantes

        Paramètres de sorties : Retourne un résultat de Type "FeatureCollection"
      parameters:
        - name: geom
          in: body
          required: true
          schema:
            $ref: "#/definitions/Geometry"

      tags:
        - Appellations
      responses:
        '200':
          description: "Succès"
          schema:
            $ref: "#/definitions/FeatureCollectionAppellationViticole"
        '400':
          description: "Paramètres invalide"
          schema:
            $ref: "#/definitions/Error"
        '500':
          description: "Erreur dans le traitement de la requête"
          schema:
            $ref: "#/definitions/Error"

definitions:

  Error:
    required:
      - code
      - message
    properties:
      code:
        type: string
      message:
        type: string

  Geometry:
    description: Une géométrie au format GeoJSON
    type: object
    properties:
      type:
        type: string
        enum:
        - Point
        - LineString
        - Polygon
        - MultiPoint
        - MultiLineString
        - MultiPolygon
        description: the geometry type

  FeatureCollectionAppellationViticole:
    description: "Liste d'objet géographique appellation viticole"
    type: object
    properties:
      type: 
        type: string
        enum:
        - FeatureCollection
      features:
        type: array
        items:
          $ref: '#/definitions/FeatureAppellationViticole'
      
  
  FeatureAppellationViticole:
    description: "Objet géographique appellation viticole" 
    type: object
    properties:
      type: 
        type: string
        enum:
        - Feature
      properties:
        type: object
        properties:
          id:
            type: string        
          id_app:
            type: string
          new_insee:
            type: string
          new_nomcom:
            type: string
          old_insee:
            type: string
          old_nomcom:
            type: string
          type_ig:
            type: string
          appellation:
            type: string
          id_denom:
            type: string
          denomination:
            type: string
          crinao:
            type: string

