openapi: '3.1.0'

info:
  version: '2.8.7'
  title: Module BDUni
  description: >

    Le service d'interrogation BDUni permet d'obtenir des informations sur les tronçons de route les plus proches d'un point.
    
    Toutes les réponses sont au format GeoJSON et de type FeatureCollection.

    Toutes les requêtes du module BDUni doivent se faire en GET.


    **Exemple de géométrie : (référentiel EPSG:4326)**

      * Point: 
        
        `{"type": "Point","coordinates":[-1.691634,48.104237]}`
  
  contact:
    name: API Carto BDUni

servers:
  - url: /

paths:
  /api/bduni/troncon:
    get:
      operationId: getTroncon
      summary: Récupération des tronçons de route les plus proches
      description: |
        Renvoie une liste de résultats contenant les données d'un troncon de route bduni à partir d'une coordonnée en longitude/latitude.
        Il faut obligatoirement renseiger les champs "lon" et "lat" ou le champ "geom" (mais pas les deux en même temps).
      parameters:

        - name: lon
          in: query
          description: 'Longitude (ex : 4.829214)'
          required: false
          schema:
            type: number
          

        - name: lat
          in: query
          description: 'Latitude (ex : 45.996981)'
          required: false
          schema:
            type: number
          

        - name: distance
          in: query
          description: 'Distance de recherche en mètres'
          required: false
          default : 100
          placeholder: 100
          schema:
            type: number
          
        
        - name: geom
          in: query
          description: Géométrie au format GeoJson
          schema:
            $ref: '#/components/schemas/Geometry'

        - name: _limit
          in: query
          description: Limite de résultats à afficher(chiffre entre 1 et 1000)
          required: false
          schema:
            type: integer
          
          
        - name: _start
          in: query
          description: Position pour le début de la recherche
          required: false
          schema:
            type: integer
          
      
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FeatureCollectionTroncon'

            
components:
  schemas:
    Coordinate:
        type: array
        items:
          type: number
        minItems: 2
        maxItems: 4
    Geometry:
      type: string
      description: Une `Geometry` au sens GeoJSON
      properties:
        type:
          type: string
          description: Le type géométrique
          enum:
            - Point
        coordinates:
          type: array
          items: {}
    Point:
      type: object
      description: Un `Point` au sens GeoJSON
      properties:
        type:
          type: string
          description: Le type géométrique (`Point`)
          enum:
            - Point
        coordinates:
          $ref: '#/components/schemas/Coordinate'
          
    Feature:
      type: object
      description: Une `Feature` au sens GeoJSON
      properties:
        type:
          type: string
          description: Le type d'objet GeoJSON (`Feature`)
        id:
          type: string
        geometry:
          $ref: '#/components/schemas/Geometry'
          
    FeatureCollection:
      type: object
      description: Une `FeatureCollection` au sens GeoJSON
      properties:
        type:
          type: string
          description: Le type d'objet GeoJSON (`FeatureCollection`)
        features:
          type: array
          items: {}
    
    FeatureTroncon:
      description: 'Un tronçon de route'
      type: object
      allOf:
        - $ref: '#/components/schemas/Feature'
      properties:
        properties:
          type: object
          properties:
            cleabs:
              type: string
            cl_admin:
              type: string
            nature:
              type: string
            pos_sol:
              type: string
            importance:
              type: string
            nb_voies:
              type: string
            sens:
              type: string
            largeur: 
              type: number
            gestion:
              type: string
            numero: 
              type: string
            distance:
              type: number
      geometry:
        $ref: '#/components/schemas/Point'

    FeatureCollectionTroncon:
      description: Une `FeatureCollection` contenant uniquement des features de type `FeatureCollectionTroncon` 
      type: object
      properties:
        type:
          type: string
          enum:
          - FeatureCollection
        features:
          type: array
          items:
            $ref: '#/components/schemas/FeatureTroncon'
