openapi: '3.1.0'
info:
  version : '2.9.2'
  title: Module Espace revendeur
  description: >

    Le service d'interrogation du module "er"  permet d'obtenir les informations  sur différentes couches de l'espace revendeur
    
    Toutes les réponses sont au format GeoJSON et de type FeatureCollection.

    Toutes les requêtes du module "er" peuvent se faire en POST ou en GET. 

    Sur cette page, vous pouvez uniquement tester les modules avec des requêtes en GET.
      
  
  contact:
    name: API Carto Espace revendeur

servers:
  - url: /
paths:
  /api/er/product:
    get:
      operationId: getProduct
      summary: Recherche des produits de l'espace revendeurs
      description: |
        Retourne un résultat de Type "FeatureCollection".
      tags:
        - product
      parameters:
        - name: code_ean
          in: query
          required: false
          schema:
            type: string

        - name: code_article
          in: query
          required: false
          schema:
            type: string
        
        - name: name
          in: query
          required: false
          schema:
            type: string
        
        - name: publication_date
          in: query
          required: false
          schema:
            type: string
        
        - name: geom
          in: query
          description: Géométrie au format GeoJson
          schema:
            $ref: '#/components/schemas/Geometry'
      
        - name: date_maj_deb
          in: query
          description: Date début de mise à jour sous la forme AAAA-MM-JJ
          required: false
          schema:
            type: string

        - name: date_maj_fin
          in: query
          description: Date fin de mise à jour sous la forme AAAA-MM-JJ
          required: false
          schema:
            type: string

        - name: publi_date_deb
          in: query
          description: Date de publication début sous la forme AAAA-MM-JJ
          required: false
          schema:
            type: string

        - name: publi_date_fin
          in: query
          description: Date de publication fin sous la forme AAAA-MM-JJ
          required: false
          schema:
            type: string

        - name: depubli_date_deb
          in: query
          description: Date de dépublication début sous la forme AAAA-MM-JJ
          required: false
          schema:
            type: string

        - name: depubli_date_fin
          in: query
          description: Date de dépublication fin sous la forme AAAA-MM-JJ
          required: false
          schema:
            type: string

        - name: _limit
          in: query
          description: Limite de résultats à afficher(chiffre entre 1 et 1000)
          required: false
          schema:
            type: integer
          
        - name: _start
          in: query
          description: Position pour le début de la recherche
          required: false
          schema:
            type: integer

        - name: _propertyNames
          in: query
          description: liste des propriétes à afficher séparées par un ;
          required: false
          schema:
            type: string

        - name: is_manufactured
          in: query
          required: false
          schema:
            type: boolean
           

      
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FeatureCollectionProduct'

  /api/er/grid:
    get:
      operationId: getGrid
      summary: Recherche des informations sur les produits
      description: |
        Retourne un résultat de Type "FeatureCollection"
      parameters:
        - name: name
          in: query
          description: Code insee de la commune sur 5 caractères
          required: false
          schema:
            type: string
            minLength: 5
            maxLength: 5

        - name: title
          in: query
          required: false
          schema:
            type: string
        
        - name: type
          in: query
          required: false
          schema:
            type: string

        - name: zip_codes
          in: query
          required: false
          schema:
            type: string
          
        - name: geom
          in: query
          description: Géométrie au format GeoJson
          schema:
            $ref: '#/components/schemas/Geometry'
          
        - name: _limit
          in: query
          description: Limite de résultats à afficher(chiffre entre 1 et 1000)
          required: false
          schema:
            type: integer
          
        - name: _start
          in: query
          description: Position pour le début de la recherche
          required: false
          schema:
            type: integer

        - name: _propertyNames
          in: query
          description: liste des propriétes à afficher séparées par un ;
          required: false
          schema:
            type: string
          
      tags:
        - grid
      responses:
        '200':
          description: Success
          content:
            application/json::
              schema:
                $ref: '#/components/schemas/FeatureCollectionGrid'

  /api/er/category:
    get:
      operationId: getCategory
      summary: Recherche d'informations en se basant sur les catégories des produits
      description: |
        Retourne un résultat de Type "FeatureCollection"

      parameters:
        - name: name
          in: query
          required: false
          schema:
            type: string

        - name: type
          in: query
          description: Les valeurs autorisées sont t ou c ou s
          required: false
          schema:
            type: string

        - name: category_id
          in: query
          required: false
          schema:
            type: string
          
        - name: geom
          in: query
          description: Géométrie au format GeoJson
          schema:
            $ref: '#/components/schemas/Geometry'
          
        - name: _limit
          in: query
          description: Limite de résultats à afficher (chiffre entre 1 et 1000)
          required: false
          schema:
            type: integer
          
        - name: _start
          in: query
          description: Position pour le début de la recherche
          required: false
          schema:
            type: integer
        
        - name: _propertyNames
          in: query
          description: liste des propriétes à afficher séparées par un ;
          required: false
          schema:
            type: string
           
      tags:
        - category
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FeatureCollectionCategory'


components:
  schemas:
    Coordinate:
      type: array
      items:
        type: number
      minItems: 2
      maxItems: 4
    Geometry:
      type: string
      description: Une `Geometry` au sens GeoJSON
      properties:
        type:
          type: string
          description: Le type géométrique
          enum:
            - Point
            - LineString
            - Polygon
            - MultiPoint
            - MultiLineString
            - MultiPolygon
        coordinates:
          type: array
          items: {}
    Feature:
      type: object
      description: Une `Feature` au sens GeoJSON
      properties:
        type:
          type: string
          description: Le type d'objet GeoJSON (`Feature`)
        id:
          type: string
        geometry:
          $ref: '#/components/schemas/Geometry'
    FeatureCollection:
      type: object
      description: Une `FeatureCollection` au sens GeoJSON
      properties:
        type:
          type: string
          description: Le type d'objet GeoJSON (`FeatureCollection`)
        features:
          type: array
          items: {}
    Point:
      type: object
      description: Un `Point` au sens GeoJSON
      properties:
        type:
          type: string
          description: Le type géométrique (`Point`)
          enum:
            - Point
        coordinates:
          $ref: '#/components/schemas/Coordinate'
    MultiPolygon:
      type: object
      description: Un `MultiPolygon` au sens GeoJSON
      properties:
        type:
          type: string
          description: Le type géométrique (`MultiPolygon`)
        coordinates:
          type: array
          items: {}
          
    #---------------------------------------------------
    # /er/product/
    #---------------------------------------------------
    
    FeatureProduct:
      description: 'Products'
      allOf:
      - $ref: '#/components/schemas/Feature'
      properties:
        properties:
          type: object
          properties:
            code_ean:
              type: string
            code_article:
              type: string
            name:
              type: string
            name_complement:
              type: string
            front_image:
              type: string
            back_image:
              type: string
            edition_number:
              type: string
            publication_date:
              type: string
            replacement:
              type: string
            dimension:
              type: string
            scale:
              type: string
            editorial:
              type: string
            sale:
              type: string
            complement:
              type: string
            category_id:
              type: string
            segment_title:
              type: string
            segment_slug:
              type: string
            theme_title:
              type: string
            theme_slug:
              type: string
            collection_title:
              type: string
            collection_slug:
              type: string
            background_color:
              type: string
            border_color:
              type: string
            pricecode:
              type: string
            price:
              type: string
            price_exlcuding_vat:
              type: string
            vat:
              type: string
            keywords:
              type: string
            ean_symb:
              type: string
            producer:
              type: string
            previous_publication_date:
              type: string
            er_visible_from:
              type: string
            er_visible_to:
              type: string
            updated_at:
              type: string
            deleted_at:
              type: string
            continent:
              type: string
            pays:
              type: string
            has_geometry:
              type: boolean
            departement:
              type: string
            region:
              type: string
            tva_type:
              type: string
            print_medium:
              type: string
            full_description:
              type: string
        geometry:
          $ref: '#/components/schemas/MultiPolygon'
  
   
    #---------------------------------------------------
    # /er/grid
    #---------------------------------------------------
              
    FeatureGrid:
      description: 'Grid'
      allOf:
        - $ref: '#/components/schemas/Feature'
      properties:
        properties:
          type: object
          properties:
            name:
              type: string
            type:
              type: string
            zip_codes:
              type: string
            title:
              type: string
            deleted:
              type: string
            children: 
              type: string
        geometry:
          $ref: '#/components/schemas/MultiPolygon'              
  
    #---------------------------------------------------
    # /er/category
    #---------------------------------------------------
    
    FeatureCategory:
      description: 'Category'
      allOf:
      - $ref: '#/components/schemas/Feature'
      properties:
        properties:
          type: object
          properties:
            code_ean:
              type: string
            code_article:
              type: string
            name:
              type: string
            name_complement:
              type: string
            front_image:
              type: string
            back_image:
              type: string
            edition_number:
              type: string
            publication_date:
              type: string
            status:
              type: string
            replacement:
              type: string
            dimension:
              type: string
            scale:
              type: string
            complement:
              type: string
            category_id:
              type: string
            segment_title:
              type: string
            segment_slug:
              type: string
            theme_title:
              type: string
            theme_slug:
              type: string
            collection_title:
              type: string
            collection_slug:
              type: string
            background_color:
              type: string
            border_color:
              type: string
            pricecode:
              type: string
            price:
              type: string
            price_exlcuding_vat:
              type: string
            vat:
              type: string
        geometry:
          $ref: '#/components/schemas/MultiPolygon'
  
    FeatureCollectionCategory:
      description: Une `FeatureCollection` contenant uniquement des features de type `FeatureCollectionCategory'` 
      allOf:
      - $ref: '#/components/schemas/FeatureCollection'
      properties:
        features:
          type: array
          items:
            $ref: '#/components/schemas/FeatureCategory'
  
    FeatureCollectionGrid:
      description: Une `FeatureCollection` contenant uniquement des features de type `FeatureCollectionGrid`
      allOf:
        - $ref: '#/components/schemas/FeatureCollection'
      properties:
        features:
          type: array
          items:
            $ref: '#/components/schemas/FeatureGrid'
  
    FeatureCollectionProduct:
      description: Une `FeatureCollection` contenant uniquement des features de type `FeatureCollectionProduit` 
      allOf:
        - $ref: '#/components/schemas/FeatureCollection'
      properties:
        features:
          type: array
          items:
            $ref: '#/components/schemas/FeatureProduct'