swagger: '2.0'
info:
  title: Module urbanisme (GpU)
  description: >
    Le service d’interrogation du GPU permet d’obtenir des informations d’urbanisme intersectant une géométrie (ponctuelle ou surfacique).
    
    Toutes les réponses sont au format GeoJSON et de type FeatureCollection.

    Exemple de géométrie :

      * Centre de Rennes : `{"type": "Point","coordinates":[-1.691634,48.104237]}`
      * Parcelle : `{"type":"MultiPolygon","coordinates":[[[[-1.6993786,48.1113366],[-1.6994647,48.1113416],[-1.6994613,48.1113573],[-1.6993639,48.111803],[-1.6992707,48.112222],[-1.6990176,48.1120599],[-1.6989945,48.1120573],[-1.6991084,48.111617],[-1.6991262,48.1115482],[-1.6993407,48.1115608],[-1.6993494,48.1115158],[-1.699361,48.111431],[-1.6993786,48.1113366]]]]}`

  version: 1.0.0

  contact:
    name: Apicarto GPU


produces:
  - application/json

basePath: /api

paths:

  /gpu/municipality:
    get:
      summary: Récupération des informations sur une commune (est au RNU? est supprimée?)
      description: |
        Retourne un résultat de Type "FeatureCollection" avec des communes correspondant aux paramètres
      tags:
        - Communes
      parameters:

        - in: query
          name: geom
          type: object
          required: false
          description: Géométrie GeoJSON utilisée pour la recherche

        - in: query
          name: insee
          type: string
          required: false
          description: Code insee de la commune
         
      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/FeatureCollection'


  /gpu/document:
    get:
      summary: Récupération de l'emprise d'un document
      description: |
        Prend en entrée une géométrie au format JSON et retourne une featureCollection.
        Retourne un résultat de Type "FeatureCollection" avec l'emprise d'un document qui intersecte la géométrie.
      tags:
        - Documents d'urbanisme (PLU, POS, CC, PSMV)
      parameters:
        - in: query
          name: geom
          type: object
          required: false
          description: Géométrie GeoJSON utilisée pour la recherche

        - in: query
          name: partition
          type: string
          required: false
          description: Partition GPU du document au format <DU/PSMV>_<INSEE/SIREN>
      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/FeatureCollection'

  /gpu/zone-urba:
    get:
      summary: Récupération des zonages d’un document d’urbanisme
      description: |
        Prend en entrée une géométrie au format JSON et retourne une featureCollection.
        Retourne un résultat de Type "FeatureCollection" avec les informations qui intersectent la géométrie.
      tags:
        - Documents d'urbanisme (PLU, POS, CC, PSMV)
      parameters:
        - in: query
          name: geom
          type: object
          required: false
          description: Géométrie GeoJSON utilisée pour la recherche

        - in: query
          name: partition
          type: string
          required: false
          description: Partition GPU du document au format <DU/PSMV>_<INSEE/SIREN>

      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/FeatureCollection'

  /gpu/secteur-cc:
    get:
      summary: Récupération des secteurs d’une carte communale
      description: >
        Prend en entrée une géométrie au format JSON et retourne une featureCollection.
        Retourne un résultat de Type "FeatureCollection" avec les informations qui intersectent la géométrie.
      tags:
        - Documents d'urbanisme (PLU, POS, CC, PSMV)
      parameters:
        - in: query
          name: geom
          type: object
          required: false
          description: Géométrie GeoJSON utilisée pour la recherche

        - in: query
          name: partition
          type: string
          required: false
          description: Partition GPU du document au format <DU/PSMV>_<INSEE/SIREN>

      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/FeatureCollection'
            
            
  /gpu/prescription-surf:
    get:
      summary: Récupération des prescriptions surfaciques d’un document d’urbanisme
      description: |
        Prend en entrée une géométrie au format JSON et retourne une featureCollection.
        Retourne un résultat de Type "FeatureCollection" avec les informations qui intersectent la géométrie.
      tags:
        - Documents d'urbanisme (PLU, POS, CC, PSMV)
      parameters:
        - in: query
          name: geom
          type: object
          required: false
          description: Géométrie GeoJSON utilisée pour la recherche

        - in: query
          name: partition
          type: string
          required: false
          description: Partition GPU du document au format <DU/PSMV>_<INSEE/SIREN>

      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/FeatureCollection'
                  
  /gpu/prescription-lin:
    get:
      summary: Récupération des prescriptions linéaires d’un document d’urbanisme
      description: |
        Prend en entrée une géométrie au format JSON et retourne une featureCollection.
        Retourne un résultat de Type "FeatureCollection" avec les informations qui intersectent la géométrie.
      tags:
        - Documents d'urbanisme (PLU, POS, CC, PSMV)
      parameters:
        - in: query
          name: geom
          type: object
          required: false
          description: Géométrie GeoJSON utilisée pour la recherche

        - in: query
          name: partition
          type: string
          required: false
          description: Partition GPU du document au format <DU/PSMV>_<INSEE/SIREN>

      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/FeatureCollection'
            
  /gpu/prescription-pct:
    get:
      summary: Récupération des prescriptions ponctuelles d’un document d’urbanisme
      description: |
        Prend en entrée une géométrie au format JSON et retourne une featureCollection.
        Retourne un résultat de Type "FeatureCollection" avec les informations qui intersectent la géométrie.
      tags:
        - Documents d'urbanisme (PLU, POS, CC, PSMV)
      parameters:
        - in: query
          name: geom
          type: object
          required: false
          description: Géométrie GeoJSON utilisée pour la recherche 

        - in: query
          name: partition
          type: string
          required: false
          description: Partition GPU du document au format <DU/PSMV>_<INSEE/SIREN>

      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/FeatureCollection'

  /gpu/info-surf:
    get:
      summary: Récupération des informations surfaciques d’un document d’urbanisme
      description: |
        Prend en entrée une géométrie au format JSON et retourne une featureCollection.
        Retourne un résultat de Type "FeatureCollection" avec les informations qui intersectent la géométrie.
      tags:
        - Documents d'urbanisme (PLU, POS, CC, PSMV)
      parameters:
        - in: query
          name: geom
          type: object
          required: false
          description: Géométrie GeoJSON utilisée pour la recherche   

        - in: query
          name: partition
          type: string
          required: false
          description: Partition GPU du document au format <DU/PSMV>_<INSEE/SIREN>

      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/FeatureCollection'

  /gpu/info-lin:
    get:
      summary: Récupération des informations linéaires d’un document d’urbanisme
      description: |
        Prend en entrée une géométrie au format JSON et retourne une featureCollection.
        Retourne un résultat de Type "FeatureCollection" avec les informations qui intersectent la géométrie.
      tags:
        - Documents d'urbanisme (PLU, POS, CC, PSMV)
      parameters:
        - in: query
          name: geom
          type: object
          required: false
          description: Géométrie GeoJSON utilisée pour la recherche

        - in: query
          name: partition
          type: string
          required: false
          description: Partition GPU du document au format <DU/PSMV>_<INSEE/SIREN>

      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/FeatureCollection'

  /gpu/info-pct:
    get:
      summary: Récupération des informations ponctuelles d’un document d’urbanisme
      description: |
        Prend en entrée une géométrie au format JSON et retourne une featureCollection.
        Retourne un résultat de Type "FeatureCollection" avec les informations qui intersectent la géométrie.
      tags:
        - Documents d'urbanisme (PLU, POS, CC, PSMV)
      parameters:
        - in: query
          name: geom
          type: object
          required: false
          description: Géométrie GeoJSON utilisée pour la recherche

        - in: query
          name: partition
          type: string
          required: false
          description: Partition GPU du document au format <DU/PSMV>_<INSEE/SIREN>

      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/FeatureCollection'


  /gpu/acte-sup:
    get:
      summary: Récupération des actes des servitudes d’utilité publique
      description: |
        Prend en entrée une géométrie au format JSON et retourne une featureCollection.
        Retourne un résultat de Type "FeatureCollection" avec les informations qui intersectent la géométrie.
      tags:
        - SUP
      parameters:
        - in: query
          name: geom
          type: object
          required: false
          description: Géométrie GeoJSON utilisée pour la recherche

        - in: query
          name: partition
          type: string
          required: false
          description: Partition GPU du document

      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/FeatureCollection'

  /gpu/assiette-sup-s:
    get:
      summary: Récupération des assiettes surfaciques de servitudes d’utilité publique
      description: |
        Prend en entrée une géométrie au format JSON et retourne une featureCollection.
        Retourne un résultat de Type "FeatureCollection" avec les informations qui intersectent la géométrie.
      tags:
        - SUP
      parameters:
        - in: query
          name: geom
          type: object
          required: false
          description: Géométrie GeoJSON utilisée pour la recherche
          
        - in: query
          name: partition
          type: string
          required: false
          description: Partition GPU du document

        - in: query
          name: categorie
          type: string
          required: false
          description: Categorie

      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/FeatureCollection'

  /gpu/assiette-sup-l:
    get:
      summary: Récupération des assiettes linéaires de servitudes d’utilité publique
      description: |
        Prend en entrée une géométrie au format JSON et retourne une featureCollection.
        Retourne un résultat de Type "FeatureCollection" avec les informations qui intersectent la géométrie.
      tags:
        - SUP
      parameters:
        - in: query
          name: geom
          type: object
          required: false
          description: Géométrie GeoJSON utilisée pour la recherche

        - in: query
          name: partition
          type: string
          required: false
          description: Partition GPU du document

        - in: query
          name: categorie
          type: string
          required: false
          description: Categorie

      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/FeatureCollection'

  /gpu/assiette-sup-p:
    get:
      summary:  Récupération des assiettes ponctuelles de servitudes d’utilité publique
      description: |
        Prend en entrée une géométrie au format JSON et retourne une featureCollection.
        Retourne un résultat de Type "FeatureCollection" avec les informations qui intersectent la géométrie.
      tags:
        - SUP
      parameters:
        - in: query
          name: geom
          type: object
          required: false
          description: Géométrie GeoJSON utilisée pour la recherche

        - in: query
          name: partition
          type: string
          required: false
          description: Partition GPU du document 

        - in: query
          name: categorie
          type: string
          required: false
          description: Categorie

      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/FeatureCollection'
  

  /gpu/generateur-sup-s:
    get:
      summary: Récupération des générateurs surfaciques des servitudes d’utilité publique
      description: |
        Prend en entrée une géométrie au format JSON et retourne une featureCollection.
        Retourne un résultat de Type "FeatureCollection" avec les informations qui intersectent la géométrie.
      tags:
        - SUP
      parameters:
        - in: query
          name: geom
          type: object
          required: false
          description: Géométrie GeoJSON utilisée pour la recherche

        - in: query
          name: partition
          type: string
          required: false
          description: Partition GPU du document

        - in: query
          name: categorie
          type: string
          required: false
          description: Categorie

      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/FeatureCollection'

  /gpu/generateur-sup-l:
    get:
      summary: Récupération des générateurs linéaires des servitudes d’utilité publique
      description: |
        Prend en entrée une géométrie au format JSON et retourne une featureCollection.
        Retourne un résultat de Type "FeatureCollection" avec les informations qui intersectent la géométrie.
      tags:
        - SUP
      parameters:
        - in: query
          name: geom
          type: object
          required: false
          description: Géométrie GeoJSON utilisée pour la recherche
    
        - in: query
          name: partition
          type: string
          required: false
          description: Partition GPU du document au format
        - in: query
          name: categorie
          type: string
          required: false
          description: Categorie

      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/FeatureCollection'

  /gpu/generateur-sup-p:
    get:
      summary:  Récupération des générateurs ponctuels des servitudes d’utilité publique
      description: |
        Prend en entrée une géométrie au format JSON et retourne une featureCollection.
        Retourne un résultat de Type "FeatureCollection" avec les informations qui intersectent la géométrie.
      tags:
        - SUP
      parameters:
        - in: query
          name: geom
          type: object
          required: false
          description: Géométrie GeoJSON utilisée pour la recherche 

        - in: query
          name: partition
          type: string
          required: false
          description: Partition GPU du document au format <DU/PSMV>_<INSEE/SIREN>

        - in: query
          name: categorie
          type: string
          required: false
          description: Categorie

      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/FeatureCollection'

  /gpu/all:
    get:
      summary:  Récupération de l’ensemble des couches décrites ci-dessus
      description: |
        Prend en entrée une géométrie au format JSON et retourne une featureCollection contenant toutes les couches du gpu qui intersectent la géométrie.
      tags:
        - All
      parameters:
        - in: query
          name: geom
          type: object
          required: false
          description: Géométrie GeoJSON utilisée pour la recherche

        - in: query
          name: partition
          type: string
          required: false
          description: Partition GPU du document au format <DU/PSMV>_<INSEE/SIREN>

        - in: query
          name: categorie
          type: string
          required: false
          description: Categorie

      responses:
        '200':
          description: Success

definitions:

  # TODO FeatureMunicility FeatureCollectionMunicipality
  # TODO FeatureZoneUrba FeatureCollectionZoneUrba
  # ...

  # import definitions
  FeatureCollection:
    $ref: './schema/geojson.yml#definitions/FeatureCollection'
  Feature:
    $ref: './schema/geojson.yml#definitions/Feature'
  Geometry:
    $ref: './schema/geojson.yml#definitions/Geometry'
  MultiPolygon:
    $ref: './schema/geojson.yml#definitions/MultiPolygon'
  Point:
    $ref: './schema/geojson.yml#definitions/Point'
