openapi: '3.1.0'

info:
  version: '2.9.0'
  title: Module Limites Administratives
  description: >

    Le service d'interrogation Limites Administratives permet d'obtenir des informations sur le découpage administratif français (régions, déparetements, communes).
    
    Toutes les réponses sont au format GeoJSON et de type FeatureCollection.

    Toutes les requêtes du module Limites Administratives peuvent se faire en POST ou en GET. 

    Sur cette page, vous pouvez uniquement tester les modules avec des requêtes en GET.


    **Exemple de géométrie : (référentiel EPSG:4326)**

      * Point: 
        
        `{"type": "Point","coordinates":[-1.691634,48.104237]}`

      * MultiPolygon: 
        
        `{"type":"MultiPolygon","coordinates":[[[[-0.288863182067871,48.963666607295977],[-0.299592018127441,48.959299208576141],[-0.296330451965332,48.955325952385039],[-0.282125473022461,48.950675995388366],[-0.279722213745117,48.967019382922331],[-0.288863182067871,48.963666607295977]]]]}`
      
      * Polygone trouée: 
          
        `{"type":"Polygon","coordinates":[[[1.2,48.85],[1.3,48.85],[1.3,48.9],[1.2,48.9],[1.2,48.85]],[[1.23,48.86],[1.23,48.88],[1.26,48.88],[1.26,48.86],[1.23,48.86]]]}`
  
      * Linéaire: 

        `{"type":"LineString","coordinates":[[4.681549,47.793784],[4.741974,47.788248]]}`
      
  
  contact:
    name: API Carto Limites Administratives

servers:
  - url: /

paths:
  /api/limites-administratives/commune:
    get:
      summary: Récupération des communes
      description: |
        Retourne un résultat de Type "FeatureCollection" avec des communes correspondant aux paramètres.
        Il faut obligatoirement renseiger les champs "lon" et "lat" ou le champ "geom" (mais pas les deux en même temps).
      parameters:

        - name: lon
          in: query
          description: 'Longitude (ex : 4.829214)'
          required: false
          schema:
            type: number
          

        - name: lat
          in: query
          description: 'Latitude (ex : 45.996981)'
          required: false
          schema:
            type: number
          
        
        - name: geom
          in: query
          description: Géométrie au format GeoJson
          required: false
          schema:
            $ref: '#/components/schemas/Geometry'

        - name: _limit
          in: query
          description: Limite de résultats à afficher(chiffre entre 1 et 1000)
          required: false
          shcema:
            type: integer
          
        - name: _start
          in: query
          description: Position pour le début de la recherche
          required: false
          schema:
            type: integer
           
      
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FeatureCollectionCommune'

  /api/limites-administratives/departement:
      get:
        summary: Récupération des départements
        description: |
          Retourne un résultat de Type "FeatureCollection" avec des départements correspondant aux paramètres.
          Il faut obligatoirement renseiger les champs "lon" et "lat" ou le champ "geom" (mais pas les deux en même temps).
        parameters:

          - name: lon
            in: query
            description: 'Longitude (ex : 4.829214)'
            required: false
            schema:
              type: number
            
          - name: lat
            in: query
            description: 'Latitude (ex : 45.996981)'
            required: false
            schema:
              type: number
          
          - name: geom
            in: query
            description: Géométrie au format GeoJson
            required: false
            schema:
              $ref: '#/components/schemas/Geometry'

          - name: _limit
            in: query
            description: Limite de résultats à afficher(chiffre entre 1 et 1000)
            required: false
            schema:
              type: integer
            
          - name: _start
            in: query
            description: Position pour le début de la recherche
            required: false
            schema:
              type: integer
            
        
        responses:
          '200':
            description: Success
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/FeatureCollectionDepartement'

  /api/limites-administratives/region:
      get:
        summary: Récupération des régions
        description: |
          Retourne un résultat de Type "FeatureCollection" avec des régions correspondant aux paramètres.
          Il faut obligatoirement renseiger les champs "lon" et "lat" ou le champ "geom" (mais pas les deux en même temps).
        parameters:

          - name: lon
            in: query
            description: 'Longitude (ex : 4.829214)'
            required: false
            schema:
              type: number

          - name: lat
            in: query
            description: 'Latitude (ex : 45.996981)'
            required: false
            schema:
              type: number

          - name: geom
            in: query
            description: Géométrie au format GeoJson
            required: false
            schema:
              $ref: '#/components/schemas/Geometry'

          - name: _limit
            in: query
            description: Limite de résultats à afficher(chiffre entre 1 et 1000)
            required: false
            schema:
              type: integer
            
          - name: _start
            in: query
            description: Position pour le début de la recherche
            required: false
            schema:
              type: integer
            
        
        responses:
          '200':
            description: Success
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/FeatureCollectionRegion'

            

components:
  schemas:
    Coordinate:
        type: array
        items:
          type: number
        minItems: 2
        maxItems: 4
    Geometry:
      type: string
      description: Une `Geometry` au sens GeoJSON
      properties:
        type:
          type: string
          description: Le type géométrique
          enum:
            - Point
            - LineString
            - Polygon
            - MultiPoint
            - MultiLineString
            - MultiPolygon
        coordinates:
          type: array
          items: {}
    Feature:
      type: object
      description: Une `Feature` au sens GeoJSON
      properties:
        type:
          type: string
          description: Le type d'objet GeoJSON (`Feature`)
        id:
          type: string
        geometry:
          $ref: '#/components/schemas/Geometry'
    FeatureCollection:
      type: object
      description: Une `FeatureCollection` au sens GeoJSON
      properties:
        type:
          type: string
          description: Le type d'objet GeoJSON (`FeatureCollection`)
        features:
          type: array
          items: {}
    MultiPolygon:
      type: object
      description: Un `MultiPolygon` au sens GeoJSON
      properties:
        type:
          type: string
          description: Le type géométrique (`MultiPolygon`)
        coordinates:
          type: array
          items: {}

  #---------------------------------------------------
  # /limites-administratives/commune/
  #---------------------------------------------------
  
    FeatureCommune:
      description: 'Une commune'
      type: object
      allOf:
        - $ref: '#/components/schemas/Feature'
      properties:
        properties:
          type: object
          properties:
            id:
              type: string
            statut:
              type: string
            insee_com:
              type: string
            nom_com:
              type: string
            nom_com_m:
              type: string
            insee_arr:
              type: string
            insee_dep:
              type: string
            nom_dep: 
              type: string
            insee_reg:
              type: string
            nom_reg: 
              type: string
            code_epci:
              type: string
            population:
              type: string
      geometry:
        $ref: '#/components/schemas/MultiPolygon'

    FeatureCollectionCommune:
      description: Une `FeatureCollection` contenant uniquement des features de type `FeatureCollectionCommune` 
      type: object
      properties:
        type:
          type: string
          enum:
          - FeatureCollection
        features:
          type: array
          items:
            $ref: '#/components/schemas/FeatureCommune'

    #---------------------------------------------------
    # /limites-administratives/departement/
    #---------------------------------------------------
    
    FeatureDepartement:
      description: 'Un département'
      type: object
      allOf:
      - $ref: '#/components/schemas/Feature'
      properties:
        properties:
          type: object
          properties:
            id:
              type: string
            insee_dep:
              type: string
            nom_dep:
              type: string
            insee_reg:
              type: string
      geometry:
        $ref: '#/components/schemas/MultiPolygon'


    FeatureCollectionDepartement:
      description: Une `FeatureCollection` contenant uniquement des features de type `FeatureCollectionDepartement` 
      type: object
      properties:
        type:
          type: string
          enum:
          - FeatureCollection
        features:
          type: array
          items:
            $ref: '#/components/schemas/FeatureDepartement'

    #---------------------------------------------------
    # /limites-administratives/region/
    #---------------------------------------------------
    
    FeatureRegion:
      description: 'Une région'
      type: object
      allOf:
      - $ref: '#/components/schemas/Feature'
      properties:
        properties:
          type: object
          properties:
            id:
              type: string
            nom_reg:
              type: string
            insee_reg:
              type: string
      geometry:
        $ref: '#/components/schemas/MultiPolygon'


    FeatureCollectionRegion:
      description: Une `FeatureCollection` contenant uniquement des features de type `FeatureCollectionRegion` 
      type: object
      properties:
        type:
          type: string
          enum: 
          - FeatureCollection
        features:
          type: array
          items:
            $ref: '#/components/schemas/FeatureRegion'
