swagger: '2.0'
info:
  title: Module Environnement
  description: >
    Le service module environnement permet de vérifier si des géométries se trouvent dans des zones protégées type parcs naturels, zones de réserves humides...
    Pour utiliser cette fonctionnalité, il faut avoir des droits sur les couches WFS Geoportail du type "PROTECTEDAREAS".
    
    L'accès à ce type de couche se fait sur demande
    à l'IGN via l'interface professionnelle après avoir créé votre clé IGN.
    
    
    ```json

    {
      "type": "FeatureCollection",
     
       "features":
       [
      
      {"type": "Feature",
      "geometry":
        
         {
           "type":"MultiPolygon",
           "coordinates":[...]
        },
        
        "geometry_name": "the_geom",
        "properties": {
          
       }
      }
    ]
    }
  
    ```

    ## Exemple d'urls à utiliser pour tester le service :
  
    Géometrie:  https://apicarto-dev.ign.fr/nature/geometrie?typeSource=rnc&geom=
    geom attends une géometrie au format GeoJson
  version: 1.0.0
  contact:
    name: Apicarto Cadastre
  license:
    name: AGPL-V3
    url: https://www.gnu.org/licenses/agpl-3.0.html
host: apicarto-dev.ign.fr
schemes:
  - https
basePath: /
produces:
  - application/json
paths:
  /nature/geometrie:
    get:
      summary: Informations  sur l'intersection d'une géométrie avec des zones environnementales
      description: |
        Prends en entrée une géométrie au format JSON et retourne une featureCollection.
        Retourne un résultat de Type "FeatureCollection" avec les informations environnementales sur les parcelles qui intersectent la géométrie.
        Les informations qui sont retournées dépdendent de la couche utilisée pour le calcul de l'intersection de la géométrie.
        
      parameters:
        - name: typeSource
          in: query
          description: abréviation de la couche à appeller
          type: string
          required: true
        - name: geom
          in: query
          description: geom est une Feature Collection
          type: string
          required: true
      tags:
        - Geometrie
      responses:
        '200':
          description: Success
          

definitions:
  Geometry:
    type: object
    description: Une `Geometry` au sens GeoJSON
    externalDocs:
      url: http://geojson.org/geojson-spec.html#geometry-objects
      description: La documentation officielle du type `Geometry` de GeoJSON
    properties:
      type:
        type: string
        enum:
        - MultiPolygon
        - Point
        description: Le type corresponds au type de Géométrie(MultiPolygon ou Point)
      coordinates:
        type: array
        items:
          type: array
          items:
            type: number

  Feature:
    type: object
    description: Une `Feature` au sens GeoJSON
    externalDocs:
      url: http://geojson.org/geojson-spec.html#feature-objects
      description: La documentation officielle du type `Feature` de GeoJSON
    properties:
      type:
        type: string
        enum:
        - Feature
        description: La valeur de type est "Feature"
      id:
        type: string
      geometry:
        $ref: '#/definitions/Geometry'
      properties:
        type: object

  FeatureCollection:
    type: object
    description: Une `FeatureCollection` au sens GeoJSON
    externalDocs:
      url: http://geojson.org/geojson-spec.html#feature-collection-objects
      description: La documentation officielle du type `FeatureCollection` de GeoJSON
    properties:
      type:
        type: string
        enum:
        - Feature
        description: Le type est FeatureCollection
      features:
        type: array
        items: object

  Geometrie:
    description: ''
    allOf:
    - $ref: '#/definitions/Feature'
    - type: object
      properties:
        properties:
          type: object
          properties:
            surface_intersection:
              type: string
            surface_parcelle:
              type: float
            numero:
              type: string
            feuille:
              type: number
            section:
              type: string
            code_dep:
              type: string
            code_com:
              type: string
            com_abs:
              type: string
            echelle:
              type: string
            code_arr:
              type: string

  Geometries:
    description: Une `FeatureCollection` contenant uniquement des features de type `Geometrie`
    allOf:
    - $ref: '#/definitions/FeatureCollection'
    - type: object
      properties:
        features:
          type: array
          items:
            $ref: '#/definitions/Geometrie'
