swagger: '2.0'
info:
  title: Module Nature
  description: >

    Le service d'interrogation du module nature  permet d'obtenir les informations  sur différentes couches réserves naturelles et natura 2000.
    
    Toutes les réponses sont au format GeoJSON et de type FeatureCollection.

    Toutes les requêtes du module cadastre peuvent se faire en POST ou en GET. 

    Sur cette page, vous pouvez uniquement tester les modules avec des requêtes en GET.

    
    Consultez la [documentation utilisateur](https://apicarto.ign.fr/api/doc/pdf/docUser_moduleNature.pdf) pour plus d’informations sur les paramètres d’appel disponibles et le format des résultats.

    ## Clé WFS géoportail (apikey)
    
      Ce service se repose sur l'appel à des services WFS de l'API géoportail de l'IGN. 
      Cette clé doit être renseignée dans le paramètre *apikey*.

      Pour obtenir une clé geoportail, vous devez vous connecter au site : https://geoservices.ign.fr.
      
      Vous ne pourrez interroger que les couches dont vous avez paramétré l'accès sur votre clé de géoservices IGN.
      La sécurisation de la clé se fait par referer.

      Si vous souhaitez utiliser les différentes ressources de ce modules vous devez commander les flux "Ressources WFS Géoportail" ci-dessous:
      
      * PROTECTEDAREAS.SIC:sic  (Sites Natura 2000 au titre de la directive Habitat)
      * PROTECTEDAREAS.ZPS:zps  (Sites NATURA 2000 au titre de la Directive Oiseaux)
      * PROTECTEDAREAS.RNN:rnn (Réserves naturelles hors Corse)
      * PROTECTEDAREAS.RNC:rnc  (Réserves Naturelles de Corse)
      * PROTECTEDAREAS.ZNIEFF1:znieff1 (Zones écologiques de nature remarquable (ZNIEFF1))
      * PROTECTEDAREAS.ZNIEFF2:znieff2  (Zones écologiques de nature remarquable (ZNIEFF2))
      * PROTECTEDAREAS.PN:pn (Parcs nationaux)
      * PROTECTEDAREAS.PNR:pnr (Parcs naturels régionaux)
      * PROTECTEDAREAS.RNCF:rncfs_fxx (Réserves nationales de chasse et de faune sauvage)


    ## Géométrie

    Bien que la géométrie des flux utilisés soit exprimée dans le référentiel WebMercator EPSG:3857, la géométrie doit être exprimée en valeur décimale dans le référentiel **WGS84 (EPSG:4326)**.
    
    La réponse en retour de l'API est elle aussi exprimée en WGS84.


    **Exemple de géométrie** : (référentiel EPSG:4326)

      * Point: 
        
        `{"type": "Point","coordinates":[-1.691634,48.104237]}`

      * MultiPolygon: 
        
        `{"type":"MultiPolygon","coordinates":[[[[4.786510231,44.799284413],[4.786771607,44.798883751],[4.786676692,44.798561391],[4.772889036,44.772781791],[4.773604638,44.773095271],[4.774237621,44.773471358],[4.775128276,44.773922006],[4.777617941,44.774676002],[4.778277786,44.774720598],[4.778921904,44.774676543],[4.786510231,44.799284413]]]]}`
      
      * Polygone troué: 
          
        `{"type":"Polygon","coordinates":[[[1.2,48.85],[1.3,48.85],[1.3,48.9],[1.2,48.9],[1.2,48.85]],[[1.23,48.86],[1.23,48.88],[1.26,48.88],[1.26,48.86],[1.23,48.86]]]}`
  
  
  contact:
    name: API Carto Nature

produces:
  - application/json

basePath: /api

paths:
  /nature/natura-habitat:
    get:
      summary: Récupération de la géométrie pour natura 2000 au titre de la directive habitat
      description: |
        Retourne un résultat de Type "FeatureCollection".
      parameters:

        - name: apikey
          in: query
          description: Clé WFS géoportail
          type: string
          required: false

        - name: sitecode
          in: query
          type: string
          required: false

        - name: geom
          in: query
          description: Géométrie au format GeoJson
          schema:
            $ref: '#/definitions/Geometry'
            
        - name: _limit
          in: query
          description: Limite de résultats à afficher(chiffre entre 1 et 1000)
          type: integer
          required: false
          
        - name: _start
          in: query
          description: Position pour le début de la recherche
          type: integer
          required: false

      tags:
        - Natura 2000 directive habitat
      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/FeatureCollectionNatura'

  /nature/natura-oiseaux:
    get:
      summary: Recherche d'informations sur les divisions parcellaires d'une commune
      description: |
        Retourne un résultat de Type "FeatureCollection"
      parameters:

        - name: apikey
          in: query
          description: Clé WFS géoportail
          type: string
          required: false

        - name: sitecode
          in: query
          type: string
          required: false
          
        - name: geom
          in: query
          description: Géométrie au format GeoJson
          schema:
            $ref: '#/definitions/Geometry'
          
        - name: _limit
          in: query
          description: Limite de résultats à afficher(chiffre entre 1 et 1000)
          type: integer
          required: false
          
        - name: _start
          in: query
          description: Position pour le début de la recherche
          type: integer
          required: false
    
      tags:
        - Natura 2000 directives oiseaux
      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/FeatureCollectionNatura'

  /nature/rnc:
    get:
      summary: Recherche d'informations sur les réserves naturelles de Corse
      description: |
        Retourne un résultat de Type "FeatureCollection"

      tags:
        - Réserves naturelles de Corse
      parameters:

        - name: apikey
          in: query
          description: Clé WFS géoportail
          type: string
          required: false

        - name: id_mnhn
          in: query
          type: string
          required: false
          
        - name: geom
          in: query
          description: Géométrie au format GeoJson
          schema:
            $ref: '#/definitions/Geometry'
          
        - name: _limit
          in: query
          description: Limite de résultats à afficher (chiffre entre 1 et 1000)
          type: integer
          required: false
          
        - name: _start
          in: query
          description: Position pour le début de la recherche
          type: integer
          required: false
    
      
      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/FeatureCollectionNatureAutre'


  /nature/rnn:
    get:
      summary: Recherche d'informations sur les réserves naturelles hors Corse
      description: |
        Retourne un résultat de Type "FeatureCollection"

      tags:
        - Réserves naturelles hors corse
      parameters:

        - name: apikey
          in: query
          description: Clé WFS géoportail
          type: string
          required: false

        - name: id_mnhn
          in: query
          type: string
          required: false
          
        - name: geom
          in: query
          description: Géométrie au format GeoJson
          schema:
            $ref: '#/definitions/Geometry'
          
        - name: _limit
          in: query
          description: Limite de résultats à afficher (chiffre entre 1 et 1000)
          type: integer
          required: false
          
        - name: _start
          in: query
          description: Position pour le début de la recherche
          type: integer
          required: false
    
      
      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/FeatureCollectionNatureAutre'
  


  /nature/znieff1:
    get:
      summary: Recherche d'informations sur des Zones écologiques de nature remarquable
      description: |
        Retourne un résultat de Type "FeatureCollection"
      
      tags:
        - znieff1
      parameters:

        - name: apikey
          in: query
          description: Clé WFS géoportail
          type: string
          required: false

        - name: id_mnhn
          in: query
          type: string
          required: false
          
        - name: geom
          in: query
          description: Géométrie au format GeoJson
          schema:
            $ref: '#/definitions/Geometry'

        - name: _limit
          in: query
          description: Limite de résultats à afficher (chiffre entre 1 et 1000)
          type: integer
          required: false
          
        - name: _start
          in: query
          description: Position pour le début de la recherche
          type: integer
          required: false

      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/FeatureCollectionNatureAutre'


  /nature/znieff2:
    get:
      summary: Recherche d'informations sur des Zones écologiques de nature remarquable
      description: Retourne un résultat de Type "FeatureCollection"
      tags:
        - znieff2
      parameters:

        - name: apikey
          in: query
          description: Clé WFS géoportail
          type: string
          required: false

        - name: id_mnhn
          in: query
          type: string
          required: false

        - name: geom
          in: query
          description: Géométrie au format GeoJson
          schema:
            $ref: '#/definitions/Geometry'
          
        - name: _limit
          in: query
          description: Limite de résultats à afficher (chiffre entre 1 et 1000)
          type: integer
          required: false
          
        - name: _start
          in: query
          description: Position pour le début de la recherche
          type: integer
          required: false

      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/FeatureCollectionNatureAutre'

  /nature/pn:
    get:
      summary: Recherche des zones dans les parcs nationaux
      description: Retourne un résultat de Type "FeatureCollection"
      tags:
        - Parcs nationaux
      parameters:

        - name: apikey
          in: query
          description: Clé WFS géoportail
          type: string
          required: false

        - name: id_mnhn
          in: query
          type: string
          required: false

        - name: geom
          in: query
          description: Géométrie au format GeoJson
          schema:
            $ref: '#/definitions/Geometry'
          
        - name: _limit
          in: query
          description: Limite de résultats à afficher (chiffre entre 1 et 1000)
          type: integer
          required: false
          
        - name: _start
          in: query
          description: Position pour le début de la recherche
          type: integer
          required: false
        
      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/FeatureCollectionNatureAutre'

  /nature/pnr:
    get:
      summary: Recherche des zones dans les  parcs naturels régionaux
      description: Retourne un résultat de Type "FeatureCollection"
      tags:
        - Parcs naturels régionaux
      parameters:

        - name: apikey
          in: query
          description: Clé WFS géoportail
          type: string
          required: false

        - name: id_mnhn
          in: query
          type: string
          required: false

        - name: geom
          in: query
          description: Géométrie au format GeoJson
          schema:
            $ref: '#/definitions/Geometry'
          
        - name: _limit
          in: query
          description: Limite de résultats à afficher (chiffre entre 1 et 1000)
          type: integer
          required: false
          
        - name: _start
          in: query
          description: Position pour le début de la recherche
          type: integer
          required: false
        
      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/FeatureCollectionNatureAutre'
  

  /nature/rncf:
    get:
      summary: Recherche des réserves nationales de chasse et de faune sauvage
      description: Retourne un résultat de Type "FeatureCollection"
      tags:
        - Réserves nationales de chasse et de faune sauvage
      parameters:

        - name: apikey
          in: query
          description: Clé WFS géoportail
          type: string
          required: false

        - name: id_mnhn
          in: query
          type: string
          required: false

        - name: geom
          in: query
          description: Géométrie au format GeoJson
          schema:
            $ref: '#/definitions/Geometry'
          
        - name: _limit
          in: query
          description: Limite de résultats à afficher (chiffre entre 1 et 1000)
          type: integer
          required: false
          
        - name: _start
          in: query
          description: Position pour le début de la recherche
          type: integer
          required: false
        
      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/FeatureCollectionNatureChassePeche'


definitions:

  #---------------------------------------------------
  # /nature/natura-habitat et natura-oiseaux
  #---------------------------------------------------
  
  FeatureNatura:
    description: 'Pour les couches natura'
    allOf:
    - $ref: '#/definitions/Feature'
    properties:
      properties:
        type: object
        properties:
          sitecode:
            type: string
          sitename:
            type: string
          url:
            type: string
      geometry:
        $ref: '#/definitions/MultiPolygon'

  FeatureCollectionNatura:
    description: Une `FeatureCollection` contenant uniquement des features de type `FeatureCommune`
    allOf:
    - $ref: '#/definitions/FeatureCollection'
    properties:
      features:
        type: array
        items:
          $ref: '#/definitions/FeatureNatura'
      geometry:
        $ref: '#/definitions/MultiPolygon'

  #---------------------------------------------------
  # /nature/
  #---------------------------------------------------
            
  FeatureNatureAutre:
    description: 'Nature autres'
    allOf:
      - $ref: '#/definitions/Feature'
    properties:
      properties:
        type: object
        properties:
          id_mnhn:
            type: string
          nom:
            type: string
          url:
            type: string
      geometry:
        $ref: '#/definitions/MultiPolygon'              

  FeatureCollectionNatureAutre:
    description: Une `FeatureCollection` contenant uniquement des features de type `FeatureDivision`
    allOf:
      - $ref: '#/definitions/FeatureCollection'
    properties:
      features:
        type: array
        items:
          $ref: '#/definitions/FeatureNatureAutre'


   #---------------------------------------------------
   # /Chasse et peche
   #---------------------------------------------------
            
  FeatureNatureChassePeche:
    description: 'Nature autres'
    allOf:
      - $ref: '#/definitions/Feature'
    properties:
      properties:
        type: object
        properties:
          id_local:
            type: string
          id_mnhn:
            type: string
          nom_site:
            type: string
          date_crea:
            type: string
          modif_adm:
            type: string
          modif_geo:
            type: string
          url_fiche:
            type: string
          surf_off:
            type: string
          acte_deb:
            type: string
          gest_site:
            type: string
          operateur:
            type: string
          precision:
            type: string
          src_geom:
            type: string
          src_annee:
            type: string
          marin:
            type: string
          p1_nature:
            type: string
          p2_culture:
            type: string
          p3_paysage:
            type: string
          p4_geologi:
            type: string
          p5_speleo:
            type: string
          p6_archeo:
            type: string
          p7_paleob:
            type: string
          p8_anthrop:
            type: string
          p9_science:
            type: string
          p10_public:
            type: string
          p11_dd:
            type: string
          p12_autre:
            type: string
      geometry:
        $ref: '#/definitions/MultiPolygon'              

  FeatureCollectionNatureChassePeche:
    description: Une `FeatureCollection` contenant uniquement des features de type `FeatureDivision`
    allOf:
      - $ref: '#/definitions/FeatureCollection'
    properties:
      features:
        type: array
        items:
          $ref: '#/definitions/FeatureNatureChassePeche'

  
  # import definitions
  FeatureCollection:
    $ref: './schema/geojson.yml#definitions/FeatureCollection'
  Feature:
    $ref: './schema/geojson.yml#definitions/Feature'
  Geometry:
    $ref: './schema/geojson.yml#definitions/Geometry'
  MultiPolygon:
    $ref: './schema/geojson.yml#definitions/MultiPolygon'
  Point:
    $ref: './schema/geojson.yml#definitions/Point'
