openapi: '3.1.0'

info:
  version: '2.9.1'
  title: Module RPG
  description: >

    Le service d’interrogation du RPG permet d’obtenir des informations du registre parcellaire graphique intersectant une géométrie (ponctuelle ou surfacique).
    
    Toutes les réponses sont au format GeoJSON et de type FeatureCollection.

    
    Toutes les requêtes du module RPG peuvent se faire en POST ou en GET. 

    
    Sur cette page, vous pouvez uniquement tester les modules avec des requêtes en GET.


    Consultez la [documentation utilisateur](https://apicarto.ign.fr/api/doc/pdf/docUser_moduleRPG.pdf) pour plus d’informations sur les paramètres d’appel disponibles et le format des résultats.
  

    Les millésimes disponibles sont :


    **RPG V1**
     
      RPG.2010:rpg_2010

      RPG.2011:rpg_2011

      RPG.2012:rpg_2012
      
      RPG.2013:rpg_2013

      RPG.2014:rpg_2014

    
    **RPG V2** 

      RPG.2015:parcelles_graphiques

      RPG.2016:parcelles_graphiques

      RPG.2017:parcelles_graphiques

      RPG.2018:parcelles_graphiques

      RPG.2019:parcelles_graphiques

      RPG.2020:parcelles_graphiques

      RPG.2021:parcelles_graphiques

      RPG.2022:parcelles_graphiques

      RPG.2023:parcelles_graphiques

      RPG.2024:parcelles_graphiques


    **Exemple de géométrie** : (référentiel EPSG:4326)

      * Point : 
        
        `{"type": "Point","coordinates":[-1.691634,48.104237]}`
      
      * MultiPolygon : 
        
        `{"type":"MultiPolygon","coordinates":[[[[-0.288863182067871,48.963666607295977],[-0.299592018127441,48.959299208576141],[-0.296330451965332,48.955325952385039],[-0.282125473022461,48.950675995388366],[-0.279722213745117,48.967019382922331],[-0.288863182067871,48.963666607295977]]]]}`

      * Polygone troué : 
        
        `{"type":"Polygon","coordinates":[[[1.2,48.85],[1.3,48.85],[1.3,48.9],[1.2,48.9],[1.2,48.85]],[[1.23,48.86],[1.23,48.88],[1.26,48.88],[1.26,48.86],[1.23,48.86]]]}`

      * Linéaire :

        `{"type":"LineString","coordinates":[[4.681549,47.793784],[4.741974,47.788248]]}`

    ## Historique des changements:

       * Suppression du paramètre *apikey*
       * La géométrie(champ geom) est obligatoire pour les recherches
     

servers:
  - url: /
paths:
  /api/rpg/v1:
    get:
      operationId: getV1
      description: |
        Prend une geometrie de type GeoJSON en paramètre d'entrée et renvoie les informations intersectant cette géométrie
        Prend une date qui sera une valeur comprise entre 2010 et 2014 inclus.
        Les champs année et geom sont obligatoires.
      parameters:

        - name: annee
          in: query
          required: true
          schema:
            type: integer
            pattern: '\d{4}'

        - name: code_cultu
          in: query
          required: false
          schema:
            type: string

        - name: geom
          in: query
          description: Le champ geom est obligatoire pour la recherche
          required: true
          schema:
            $ref: "#/components/schemas/Geometry"

        - name: _limit
          in: query
          description: Limite de résultats à afficher (chiffre entre 1 et 1000)
          required: false
          schema:
            type: integer
          
        - name: _start
          in: query
          description: Position pour le début de la recherche
          required: false
          schema:
            type: integer

      tags:
        - RPG avant 2015
      responses:
        '200':
          description: "Succès"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/FeatureCollectionRPGAvant2015"

  /api/rpg/v2:
    get:
      operationId: getV2
      description: |
        Prend une geometrie de type GeoJSON en paramètre d'entrée et renvoie les informations intersectant cette géométrie
        Prend une date qui sera une valeur comprise entre 2015 et 2024 inclus.
        Les champs année et geom sont obligatoires.
        
      parameters:
        - name: annee
          in: query
          required: true
          schema:
            type: integer
            pattern: '\d{4}'

        - name: code_cultu
          in: query
          required: false
          schema:
            type: string

        - name: geom
          in: query
          description: Le champ geom est obligatoire pour la recherche
          required: true
          schema:
            $ref: "#/components/schemas/Geometry"

        - name: _limit
          in: query
          description: Limite de résultats à afficher (chiffre entre 1 et 1000)
          required: false
          schema:
            type: integer
          
        - name: _start
          in: query
          description: Position pour le début de la recherche
          required: false
          schema:
            type: integer

      tags:
        - RPG à partir de 2015
      responses:
        '200':
          description: "Succès"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/FeatureCollectionRPGApartirde2015"

components:            
  schemas:
      Coordinate:
        type: array
        items:
          type: number
        minItems: 2
        maxItems: 4
      Geometry:
        type: string
        description: Une `Geometry` au sens GeoJSON
        properties:
          type:
            type: string
            description: Le type géométrique
            enum:
              - Point
              - LineString
              - Polygon
              - MultiPoint
              - MultiLineString
              - MultiPolygon
          coordinates:
            type: array
            items: {}
      Feature:
        type: object
        description: Une `Feature` au sens GeoJSON
        properties:
          type:
            type: string
            description: Le type d'objet GeoJSON (`Feature`)
          id:
            type: string
          geometry:
            $ref: '#/components/schemas/Geometry'
      FeatureCollection:
        type: object
        description: Une `FeatureCollection` au sens GeoJSON
        properties:
          type:
            type: string
            description: Le type d'objet GeoJSON (`FeatureCollection`)
          features:
            type: array
            items: {}
      MultiPolygon:
        type: object
        description: Un `MultiPolygon` au sens GeoJSON
        properties:
          type:
            type: string
            description: Le type géométrique (`MultiPolygon`)
          coordinates:
            type: array
            items: {}

      FeatureRPGApartirde2015:
        description: "Objet géographique RPG à partir de 2015" 
        type: object
        allOf:
          - $ref: "#/components/schemas/Feature"
        properties:
          properties:
            type: object
            properties:
              id_parcel:
                type: string        
              surf_parc:
                type: string
              code_cultu:
                type: string
              code_group:
                type: string
              culture_d1:
                type: string
              culture_d2:
                type: string
    
          geometry:
            $ref: '#/components/schemas/MultiPolygon'
    
      FeatureCollectionRPGApartirde2015:
        description: "Liste d'objet géographique RPG"
        type: object
        properties:
          type: 
            type: string
            enum:
            - FeatureCollection
          features:
            type: array
            items:
              $ref: '#/components/schemas/FeatureRPGApartirde2015'
    
      FeatureRPGAvant2015:
        description: "Objet géographique RPG avant 2015" 
        type: object
        allOf:
          - $ref: "#/components/schemas/Feature"
        properties:
          properties:
            type: object
            properties:
              num_ilot:
                type: string        
              commune:
                type: string
              forme_juri:
                type: string
              surf_decla:
                type: string
              dep_rattach:
                type: string
              surf_cultu:
                type: string
              code_cultu:
                type: string
              nom_cultu:
                type: string
    
          geometry:
            $ref: '#/components/schemas/MultiPolygon'
    
      FeatureCollectionRPGAvant2015:
        description: "Liste d'objet géographique RPG"
        type: object
        properties:
          type: 
            type: string
            enum:
            - FeatureCollection
          features:
            type: array
            items:
              $ref: '#/components/schemas/FeatureRPGAvant2015'
      